/**
 * MCP trace-to-edit mapping handler.
 * Converts AgentLoop Act step output into incremental WorkspaceEdit instructions.
 *
 * DEBT-W3-TRACE-EDIT-001: Edit chunks are generated from mock code analysis.
 * Real Rust AgentLoop integration deferred to Week 4-5 (FFI bridge).
 */

import { validateQuery } from './trace_handler';

/** Single edit instruction for incremental code modification. */
export interface EditInstruction {
  uri: string;
  range: [number, number, number, number];
  text: string;
  description: string;
}

/** Union type of all events yielded by the trace-to-edit stream. */
export type TraceEditEvent =
  | { type: 'trace'; payload: { step: string; details: string; iteration: number } }
  | { type: 'edit'; payload: EditInstruction }
  | { type: 'complete'; payload: Record<string, never> }
  | { type: 'error'; payload: { message: string } };

const TRACE_STEPS = ['Observe', 'Retrieve', 'Plan', 'Act', 'Reflect', 'Store', 'Decide'];
const STEP_DELAY_MS = 60;

/**
 * Stream trace events interleaved with edit instructions.
 * During the Act step, edit chunks are yielded after the trace event.
 */
export async function* streamTraceToEdit(query: string): AsyncGenerator<TraceEditEvent> {
  const q = validateQuery(query);
  try {
    for (let i = 0; i < TRACE_STEPS.length; i++) {
      const step = TRACE_STEPS[i];
      yield { type: 'trace', payload: { step, details: `${step}: ${q}`, iteration: i } };

      if (step === 'Act') {
        for await (const edit of generateMockEdits(q)) {
          yield { type: 'edit', payload: edit };
        }
      }

      await new Promise<void>((r) => setTimeout(r, STEP_DELAY_MS));
    }
    yield { type: 'complete', payload: {} };
  } catch (err) {
    yield {
      type: 'error',
      payload: { message: err instanceof Error ? err.message : String(err) },
    };
  }
}

/**
 * Map a LoopState step to the edit lifecycle phase.
 * - 'start':  stream begins (Act)
 * - 'stream': edits are flowing (Act)
 * - 'end':    stream should finalize (Reflect)
 * - 'none':   no edit activity
 */
export function traceToEditStep(step: string): 'start' | 'stream' | 'end' | 'none' {
  if (step === 'Act') return 'stream';
  if (step === 'Reflect') return 'end';
  return 'none';
}

/**
 * Apply a list of edit instructions to a text content string.
 * Returns the modified text (preview-mode simulation, not real WorkspaceEdit).
 */
export function applyEditsToContent(content: string, edits: EditInstruction[]): string {
  let result = content;
  // Apply edits in reverse order to preserve line numbers
  for (let i = edits.length - 1; i >= 0; i--) {
    const edit = edits[i];
    const lines = result.split('\n');
    const [sl, sc, el, ec] = edit.range;
    const startIdx = Math.min(sl, Math.max(0, lines.length - 1));
    const endIdx = Math.min(el, Math.max(0, lines.length - 1));
    const before = lines[startIdx].slice(0, sc);
    const after = lines[endIdx].slice(ec);
    const replacement = edit.text.split('\n');
    replacement[0] = before + replacement[0];
    replacement[replacement.length - 1] = replacement[replacement.length - 1] + after;
    lines.splice(startIdx, endIdx - startIdx + 1, ...replacement);
    result = lines.join('\n');
  }
  return result;
}

/** Heuristic mock edit generator based on query keywords. */
async function* generateMockEdits(query: string): AsyncGenerator<EditInstruction> {
  const lower = query.toLowerCase();

  if (lower.includes('add') || lower.includes('create')) {
    yield {
      uri: 'src/example.ts',
      range: [0, 0, 0, 0],
      text: `// Auto-generated by Hajimi: ${query}\n`,
      description: 'Add trace comment header',
    };
    yield {
      uri: 'src/example.ts',
      range: [1, 0, 1, 0],
      text: `export function newFeature(): void {\n  // TODO: implement based on "${query}"\n}\n`,
      description: 'Add new feature function skeleton',
    };
  } else if (lower.includes('fix') || lower.includes('bug')) {
    yield {
      uri: 'src/example.ts',
      range: [0, 0, 0, 0],
      text: `// Fixed by Hajimi: ${query}\n`,
      description: 'Add fix trace comment',
    };
    yield {
      uri: 'src/example.ts',
      range: [10, 0, 10, 20],
      text: 'fixedCode() // patched',
      description: 'Apply bug fix on line 10',
    };
  } else if (lower.includes('update') || lower.includes('change')) {
    yield {
      uri: 'src/example.ts',
      range: [5, 0, 5, 15],
      text: `updatedValue /* ${query} */`,
      description: 'Update existing value',
    };
  } else if (lower.includes('remove') || lower.includes('delete')) {
    yield {
      uri: 'src/example.ts',
      range: [3, 0, 3, 30],
      text: '',
      description: 'Remove deprecated line',
    };
  } else {
    yield {
      uri: 'src/example.ts',
      range: [0, 0, 0, 0],
      text: `// Hajimi trace: ${query}\n`,
      description: 'Add generic trace comment',
    };
  }

  await new Promise<void>((r) => setTimeout(r, 40));
}

/** Convert edit instructions to a JSON-serializable format for MCP tool responses. */
export function editsToJSON(edits: EditInstruction[]): string {
  return JSON.stringify({ edits, count: edits.length }, null, 2);
}

/** Check if a query implies code edits (contains add/fix/create/change keywords). */
export function impliesCodeEdit(query: string): boolean {
  const keywords = ['add', 'fix', 'create', 'change', 'update', 'remove', 'delete', 'refactor'];
  return keywords.some((k) => query.toLowerCase().includes(k));
}
